#!/usr/bin/env bash

backup_folder="$HOME/Dropbox/Backups/$(hostname)"

test -d "$backup_folder" || mkdir -p "$backup_folder"

datestamp=$(date +%Y-%m-%d)

cp $HOME/.bash_history "$backup_folder/bash_history_$datestamp"

