#!/usr/bin/env bash

input="$1"
test -z "$input" || die "Usage: gifgen input-file [output] [scale]"
output="$2"
if [[ -z "$output" ]]; then
  output="${input%%.*}.gif"
fi
scale="$3"
if [[ -z "$scale" ]]; then
  scale="320:-1"
fi

palette="/tmp/palette.png"
filters="fps=15,scale=$scale:flags=lanczos"

ffmpeg -i "$1" -vf "$filters,palettegen" -y "$palette"
ffmpeg -i "$1" -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $output

