#!/bin/sh

export OPENAI_MAX_TOKENS=4096
export OPENAI_SYSTEM="You are a helpful assistant, provide a short first sentence, followed by two newlines with an optional description of the changes. Just provide the text of the commit message, nothing else, no explanations."
Q "Write a commit message for the following changeset:\n\`\`\`$(git staged)\`\`\`" \
| git commit --file=- --edit $@

