#!/usr/bin/env bash

if test -z "$GOOGLE_APPLICATION_CREDENTIALS"; then
  echo "Missing environment variable GOOGLE_APPLICATION_CREDENTIALS" >&2
  exit 1
fi

gcloud auth login $@ \
&& (yes | gcloud auth application-default login $@) \
&& mv ~/.config/gcloud/application_default_credentials.json $GOOGLE_APPLICATION_CREDENTIALS

