#!/bin/bash

if [ $# -ge 1 -a -f "$1" ]; then
  files=$@
else
  files=/dev/stdin
fi

for file in $files; do
  # Quickly peek at secrets stored in kubernetes yaml/json files (base64 encoded)
  yaml-to-json < $file \
  | jq '
    [
      select(.kind == "Secret")
      | .data
      | to_entries[]
      | .value = (.value | @base64d)
    ]
    | from_entries'
done

