#!/bin/bash

# Quickly peek at secrets stored in kubernetes yaml files (base64 encoded)

for file in $@; do
  echo "${file}:"
  yaml2json < $file \
  | jq '[.select(.type == "Secret")
    | .data
    | to_entries[]
    | .value = (.value | @base64d)]
    | from_entries
  '
done

