#!/usr/bin/env bash

set -e
test "$(id -u)" -eq 0 || die "This script needs to run as root"

# obtain a username
username="$1"
if [[ "x" = "x$username" ]]; then
  read -p "Enter the user name: " username
fi
username="$(lower $username)"

# check that user does not already exist
if [[ "$username" == $(dscl . -list /Users UniqueID | awk '{print $1}' | grep -w $username) ]]; then
  die "User already exists!"
fi

# generate sensible defaults
realname=$(titleize $username)
lastid=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1)
unique_id=$((lastid + 1))
password="$(random-word)-$(random-word)-$(random-word)"

# like adduser but macos
dscl . -create /Users/$username
dscl . -create /Users/$username UserShell "$SHELL"
dscl . -create /Users/$username RealName "$realname"
dscl . -create /Users/$username UniqueID "$unique_id"
dscl . -create /Users/$username PrimaryGroupID 20
dscl . -create /Users/$username NFSHomeDirectory /Users/$username
dscl . -passwd /Users/$username $password
dscl . -create /Users/$username hint ""
createhomedir -u $username -c
# normal users are member of staff
dseditgroup -o edit -t user -a $username staff

echo "New user $username has been created with unique ID $unique_id"
echo "New user password: $password"

