#!/usr/bin/env bash -e

OPENAI_BASE_URL="${OPENAI_BASE_URL:=https://api.openai.com}"
OPENAI_ORGANIZATION_KEY="$OPENAI_ORGANIZATION_KEY"
OPENAI_MODEL="${OPENAI_MODEL:=gpt-5.2}"
OPENAI_API_KEY="$OPENAI_API_KEY"
OPENAI_SYSTEM="${OPENAI_SYSTEM:=You are a helpful assistant.}"
OPENAI_MAX_TOKENS="${OPENAI_MAX_TOKENS:=2048}"
OPENAI_REASONING_EFFORT="${OPENAI_REASONING_EFFORT}"

if [[ "$1" = "-" ]]; then
  content="$(cat)"
elif test "$#" -gt 0; then
  content="$@"
else
  content="$(gum input --placeholder 'Write a query')"
fi

curl -XPOST  "${OPENAI_BASE_URL}/v1/responses" \
  --silent \
  --fail \
  --no-buffer \
  -H"Content-Type: application/json" \
  -H"Authorization: Bearer $OPENAI_API_KEY" \
  -d"$(
    jq --null-input \
      --arg model "$OPENAI_MODEL" \
      --arg content "$content" \
      --arg system "$OPENAI_SYSTEM" \
      --arg max_tokens "$OPENAI_MAX_TOKENS" \
      --arg reasoning_effort "$OPENAI_REASONING_EFFORT" \
      '{
          "model": $model,
          "instructions": $system,
          "input": $content,
          "store": false,
          "stream": true,
          "max_output_tokens": $max_tokens | tonumber
      }
      + (if $reasoning_effort != "" then { "reasoning": { "effort": $reasoning_effort } } else {} end)
    '
  )" \
| grep -A2 'event: response.output_text.delta' \
| sed -e '/^event/d' -e 's/^data: //' \
| jq --join-output --unbuffered '.delta'

