#!/usr/bin/env bash
# Found on https://gist.github.com/asv/a286b8aefb972af8f62c

if [[ -p /dev/stdin ]]; then
  string="$(cat -)"
else
  string="$@"
fi

string_arr=($string)

echo "${string_arr[*]^}"

