source ~/.config/nvim/plug.vim
source ~/.config/nvim/plugins.vim
source ~/.config/nvim/plugins/coc.vim
source ~/.config/nvim/plugins/fzf.vim
source ~/.config/nvim/plugins/autopairs.vim
source ~/.config/nvim/plugins/ai.vim
source ~/.config/nvim/config.vim
source ~/.config/nvim/treesitter-config.vim
source ~/.config/nvim/commands.vim
